# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/lintr

env:
  - PACKAGE_VERSION="0.3.1.9000"

os:
  - linux
  - osx

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'covr::codecov()'
  - make test-nocache
  - Rscript -e 'lintr::lint_package()'
