# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true

r_github_packages:
  - jimhester/lintr

env:
  - PACKAGE_VERSION="0.3.1.9000"

os:
  - linux
  - osx

before_script:
  - curl -L https://raw.githubusercontent.com/rdatsci/travis-r-tools/master/update-packages.r -o /tmp/update-packages.r
  - Rscript /tmp/update-packages.r

after_success:
    - Rscript -e 'covr::codecov()'
    - make test-nocache
    - Rscript -e 'lintr::lint_package()'
